apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.haproxy.name }}
  namespace: {{ $.Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
  - name: metrics
    port: 9090
  selector:
    k8s-app: {{ $.Values.haproxy.name }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.haproxy.name }}-0
  namespace: {{ $.Values.namespace }}
spec:
  ports:
  - name: peering
    port: 1024
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.haproxy.name }}-1
  namespace: {{ $.Values.namespace }}
spec:
  ports:
  - name: peering
    port: 1024
  type: ClusterIP
