{{ if (gt ($.Values.shardCount | int) 1) -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    k8s-app: {{ $.Values.haproxy.name }}
  name: {{ $.Values.haproxy.name }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: {{ $.Values.haproxy.name }}
  serviceName: {{ $.Values.haproxy.name }}
  template:
    metadata:
      labels:
        k8s-app: {{ $.Values.haproxy.name }}
      annotations:
        checksum/config: {{ tpl (.Files.Get "configs/haproxy/haproxy.cfg") . | sha256sum }}
    spec:
    {{- with $.Values.haproxy.extraPodSpec }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    
    {{- if (($.Values.global).serviceAccount) }}
      serviceAccountName: {{ (($.Values.global).serviceAccount) }}
    {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values:
                - {{ $.Values.haproxy.name }}
            topologyKey: topology.kubernetes.io/zone
      containers:
      - env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: {{ $.Values.haproxy.image }}
        name: haproxy
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        - containerPort: 1024
          name: peering
        readinessProbe:
          httpGet:
            path: /stats
            port: metrics
        startupProbe:
          httpGet:
            path: /stats
            port: metrics
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: haproxy-config
          subPath: haproxy.cfg
      {{- with $.Values.haproxy.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      volumes:
      - configMap:
          items:
          - key: haproxy.cfg
            path: haproxy.cfg
          name: haproxy-config
        name: haproxy-config
{{ end -}}
