{{ if ne $.Values.metacontrollerNamespace "" -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: metacontroller
  name: metacontroller
  namespace: {{ $.Values.metacontrollerNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metacontroller
  serviceName: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metacontroller
    spec:
      serviceAccountName: {{ (($.Values.global).metacontrollerServiceAccount) | default "metacontroller" }}
      containers:
      - name: metacontroller
        image: metacontrollerio/metacontroller:v1.5.8
        command: ["/usr/bin/metacontroller"]
        args:
        - --logtostderr
        - -v=4
        - --discovery-interval=20s
  volumeClaimTemplates: []
{{ end -}}
