# This daemon set increases network buffer size on nodes hosting the JVBs
# cf https://github.com/jitsi/jitsi-videobridge/blob/master/config/20-jvb-udp-buffers.conf
{{ if $.Values.jvb.sysctlDaemonSetEnable -}}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: sysctl-jvb
    scope: jitsi
  name: sysctl-jvb
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    matchLabels:
      k8s-app: sysctl-jvb
      scope: jitsi
  template:
    metadata:
      labels:
        k8s-app: sysctl-jvb
        scope: jitsi
    spec:
    {{- with $.Values.jvb.extraPodSpec }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if (($.Values.global).serviceAccount) }}
      serviceAccountName: {{ (($.Values.global).serviceAccount) }}
    {{- end }}
      hostNetwork: yes
      containers:
      - name: sysctl-jvb
        image: alpine
        securityContext:
          privileged: true
        command:
        - /bin/sh
        - -c
        - |
          set -o errexit
          set -o xtrace
          while sysctl -w net.core.rmem_max=10485760 net.core.wmem_max=10485760 net.core.netdev_max_backlog=100000
          do
            sleep 60s
          done
{{ end -}}
